#!/usr/bin/env python3
"""Render README skill and plugin directory blocks."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from repository_collections import NPX_ADD_PREFIX, collection_readmes, discovered_collections


ROOT = Path(__file__).resolve().parents[1]
SEMVER_NUMBER = r"(?:0|[1-9]\d*)"
SEMVER_PRERELEASE = rf"(?:{SEMVER_NUMBER}|\d*[A-Za-z-][0-9A-Za-z-]*)"
SEMVER_PATTERN = re.compile(
    rf"^{SEMVER_NUMBER}\.{SEMVER_NUMBER}\.{SEMVER_NUMBER}"
    rf"(?:-{SEMVER_PRERELEASE}(?:\.{SEMVER_PRERELEASE})*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
README_CONFIGS = (
    {
        "path": ROOT / "README.md",
        "skills_header": ("Skill", "Collection", "Version", "Description"),
        "plugins_header": (
            "Plugin",
            "Harness",
            "Category",
            "Version",
            "Description",
        ),
    },
    {
        "path": ROOT / "README.zh-CN.md",
        "skills_header": ("Skill", "主题", "版本", "描述"),
        "plugins_header": ("Plugin", "Harness", "分类", "版本", "描述"),
    },
)
class RenderError(Exception):
    """Raised when README directory rendering cannot proceed."""


def load_json(path: Path) -> dict:
    try:
        with path.open(encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError as exc:
        raise RenderError(f"Missing JSON file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise RenderError(f"Invalid JSON in {path.relative_to(ROOT)}: {exc}") from exc


def markdown_cell(value: object) -> str:
    text = "" if value is None else str(value)
    text = " ".join(text.split())
    return text.replace("|", "\\|")


def first_sentence(text: str) -> str:
    chinese_stop = text.find("。")
    if chinese_stop != -1:
        return text[: chinese_stop + 1].strip()
    match = re.search(r"(?<=[。.!?])\s", text)
    if match:
        return text[: match.start() + 1].strip()
    return text.strip()


def parse_skill_front_matter(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise RenderError(f"Missing front matter in {path.relative_to(ROOT)}")

    end = text.find("\n---", 4)
    if end == -1:
        raise RenderError(f"Unclosed front matter in {path.relative_to(ROOT)}")

    values: dict[str, str] = {}
    metadata_values: dict[str, str] = {}
    in_metadata = False
    for raw_line in text[4:end].splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        if ":" not in raw_line:
            continue
        key, raw_value = raw_line.split(":", 1)
        value = raw_value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        if raw_line[:1].isspace():
            if in_metadata:
                metadata_values[key.strip()] = value
            continue
        in_metadata = key.strip() == "metadata"
        values[key.strip()] = value

    name = values.get("name") or path.parent.name
    description = values.get("description")
    if not description:
        raise RenderError(f"Missing description in {path.relative_to(ROOT)}")
    version = metadata_values.get("version")
    if not version:
        raise RenderError(f"Missing metadata.version in {path.relative_to(ROOT)}")
    if not SEMVER_PATTERN.fullmatch(version):
        raise RenderError(
            f"Invalid metadata.version in {path.relative_to(ROOT)}: {version}"
        )
    return name, version, first_sentence(description)


def skill_paths() -> list[Path]:
    skills_root = ROOT / "skills"
    flat = list(skills_root.glob("*/SKILL.md"))
    nested = list(skills_root.glob("*/*/SKILL.md"))
    for flat_skill in flat:
        if any(flat_skill.parent.glob("*/SKILL.md")):
            raise RenderError(
                "Collection root cannot contain SKILL.md: "
                f"{flat_skill.relative_to(ROOT)}"
            )
    return sorted([*flat, *nested])


def skill_collection(skill_path: Path) -> str:
    parts = skill_path.relative_to(ROOT / "skills").parts
    return parts[0] if len(parts) == 3 else "—"


def render_skills(headers: tuple[str, str, str, str]) -> str:
    rows = [
        "<!-- generated by scripts/render-plugin-directory.py; do not edit manually -->",
        "",
        f"| {headers[0]} | {headers[1]} | {headers[2]} | {headers[3]} |",
        "|---|---|---:|---|",
    ]

    seen_names: set[str] = set()
    for skill_path in skill_paths():
        name, version, description = parse_skill_front_matter(skill_path)
        if name in seen_names:
            raise RenderError(f"Duplicate standalone skill name: {name}")
        if name != skill_path.parent.name:
            raise RenderError(
                f"Skill name {name} does not match directory "
                f"{skill_path.parent.relative_to(ROOT)}"
            )
        seen_names.add(name)
        link = f"./{skill_path.relative_to(ROOT).as_posix()}"
        rows.append(
            "| "
            + " | ".join(
                [
                    f"[{markdown_cell(name)}]({link})",
                    markdown_cell(skill_collection(skill_path)),
                    markdown_cell(version),
                    markdown_cell(description),
                ]
            )
            + " |"
        )

    return "\n".join(rows)


def plugin_description(plugin_manifest: dict) -> str:
    interface = plugin_manifest.get("interface")
    if isinstance(interface, dict) and interface.get("shortDescription"):
        return str(interface["shortDescription"])
    return str(plugin_manifest.get("description") or "")


def plugin_link(plugin_dir: Path) -> str:
    readme = plugin_dir / "README.md"
    target = readme if readme.exists() else plugin_dir
    return f"./{target.relative_to(ROOT).as_posix()}"


def render_plugins(headers: tuple[str, str, str, str, str]) -> str:
    rows = [
        "<!-- generated by scripts/render-plugin-directory.py; do not edit manually -->",
        "",
        (
            f"| {headers[0]} | {headers[1]} | {headers[2]} | "
            f"{headers[3]} | {headers[4]} |"
        ),
        "|---|---|---|---:|---|",
    ]

    for plugin_dir in sorted(path for path in (ROOT / "plugins").iterdir() if path.is_dir()):
        manifests: list[tuple[str, dict]] = []
        for harness, relative_path in (
            ("Codex", Path(".codex-plugin/plugin.json")),
            ("Claude Code", Path(".claude-plugin/plugin.json")),
        ):
            manifest_path = plugin_dir / relative_path
            if manifest_path.is_file():
                manifests.append((harness, load_json(manifest_path)))
        if not manifests:
            raise RenderError(f"Plugin has no supported manifest: {plugin_dir.relative_to(ROOT)}")

        plugin_name = manifests[0][1].get("name")
        shared_fields = (
            "name",
            "version",
            "description",
            "author",
            "license",
            "keywords",
            "skills",
            "mcpServers",
        )
        if plugin_name == "code-atlas":
            shared_fields = tuple(field for field in shared_fields if field != "mcpServers")
        for field in shared_fields:
            values = [manifest.get(field) for _, manifest in manifests]
            if any(value is None for value in values) or any(
                value != values[0] for value in values[1:]
            ):
                raise RenderError(
                    f"Plugin manifest {field} differs in "
                    f"{plugin_dir.relative_to(ROOT)}"
                )
        for _, candidate in manifests:
            for field in ("skills", "hooks", "mcpServers"):
                value = candidate.get(field)
                if isinstance(value, str) and not (plugin_dir / value).exists():
                    raise RenderError(
                        f"Plugin manifest {field} path does not exist: "
                        f"{plugin_dir.relative_to(ROOT) / value}"
                    )
        name = manifests[0][1]["name"]
        version = manifests[0][1]["version"]
        manifest = manifests[0][1]
        interface = manifest.get("interface")
        category = interface.get("category", "") if isinstance(interface, dict) else ""

        rows.append(
            "| "
            + " | ".join(
                [
                    f"[{markdown_cell(name)}]({plugin_link(plugin_dir)})",
                    markdown_cell(", ".join(harness for harness, _ in manifests)),
                    markdown_cell(category),
                    markdown_cell(version),
                    markdown_cell(plugin_description(manifest)),
                ]
            )
            + " |"
        )

    return "\n".join(rows)


def render_collection(collection: str) -> str:
    members = [
        path
        for path in skill_paths()
        if skill_collection(path) == collection
    ]
    if not members:
        raise RenderError(f"Collection has no skills: {collection}")

    rows = [
        "<!-- generated by scripts/render-plugin-directory.py; do not edit manually -->",
        "",
        "| Skill | 版本 | 描述 |",
        "|---|---:|---|",
    ]
    names: list[str] = []
    for skill_path in members:
        name, version, description = parse_skill_front_matter(skill_path)
        names.append(name)
        rows.append(
            f"| [{markdown_cell(name)}](./{name}/SKILL.md) | "
            f"{markdown_cell(version)} | {markdown_cell(description)} |"
        )

    skill_args = " ".join(f"--skill {name}" for name in names)
    rows.extend(
        [
            "",
            "从 `main` 安装本主题当前全部 skills：",
            "",
            "```bash",
            f"{NPX_ADD_PREFIX} {skill_args}",
            "```",
        ]
    )
    return "\n".join(rows)


def replace_block(text: str, block_name: str, rendered: str) -> str:
    start = f"<!-- {block_name}_START -->"
    end = f"<!-- {block_name}_END -->"
    pattern = re.compile(
        rf"{re.escape(start)}\n.*?\n{re.escape(end)}",
        flags=re.DOTALL,
    )
    replacement = f"{start}\n{rendered}\n{end}"
    updated, count = pattern.subn(replacement, text)
    if count != 1:
        raise RenderError(f"Expected exactly one {block_name} block")
    return updated


def render_readme(config: dict[str, object]) -> str:
    path = config["path"]
    assert isinstance(path, Path)
    text = path.read_text(encoding="utf-8")
    text = replace_block(text, "SKILLS", render_skills(config["skills_header"]))
    text = replace_block(text, "PLUGINS", render_plugins(config["plugins_header"]))
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if README directory blocks are stale",
    )
    args = parser.parse_args()

    try:
        changed: list[Path] = []
        for config in README_CONFIGS:
            path = config["path"]
            assert isinstance(path, Path)
            rendered = render_readme(config)
            current = path.read_text(encoding="utf-8")
            if rendered != current:
                changed.append(path)
                if not args.check:
                    path.write_text(rendered, encoding="utf-8")
        collections = discovered_collections(ROOT)
        readmes = collection_readmes(ROOT)
        if set(collections) != set(readmes):
            missing = sorted(set(collections) - set(readmes))
            orphaned = sorted(set(readmes) - set(collections))
            raise RenderError(
                f"Collection README mismatch; missing={missing}, orphaned={orphaned}"
            )
        for collection in collections:
            path = readmes[collection]
            rendered = replace_block(
                path.read_text(encoding="utf-8"),
                "COLLECTION_MEMBERS",
                render_collection(collection),
            )
            if rendered != path.read_text(encoding="utf-8"):
                changed.append(path)
                if not args.check:
                    path.write_text(rendered, encoding="utf-8")

        if args.check and changed:
            rel_paths = ", ".join(path.relative_to(ROOT).as_posix() for path in changed)
            print(
                "README directory blocks are stale. Run "
                "python3 scripts/render-plugin-directory.py. "
                f"Stale files: {rel_paths}",
                file=sys.stderr,
            )
            return 1
    except RenderError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
